### ISSUE TITLE
Node.js 20 workflow causes issues with modbus and mbus binding (related to serialport)

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1004]
We need to investigate the reason why Node.js 20 is not working as expected

----
A proposal could be to run Node.js 16 and 18 only (for now) and we investigate why mbus and modbus are failing with Node.js 20.
What do you think?

_Originally posted by @danielpeintner in https://github.com/eclipse-thingweb/node-wot/issues/995#issuecomment-1553062342_

**Comment by vcharpenay** [comment]
For what it's worth, I also get an error with Node.js v18.16.1:

```
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/victor.charpenay/.npm/_cacache/tmp/git-cloneqLIH1l/node_modules/node-mbus
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node-gyp rebuild
```

I updated dependencies in my project from `0.7.0` to `eclipse-thingweb/node-wot#0f6c5f8` (to test the fix pushed in this commit) but with`npm i`, I then get the error above.

**Comment by danielpeintner** [comment]
This is **very** strange, since the CI builds and runs work fine.
I locally use Node v18.14.2 without any issues..
Is @vcharpenay the only one experiencing this kind of issue?

**Comment by JKRhb** [comment]
I just opened a PR (https://github.com/Apollon77/node-mbus/pull/104) in the `node-mbus` repository that will hopefully contribute to resolving this issue :)

**Comment by danielpeintner** [comment]
@JKRhb do you think a *similar* fix is needed for a modbus dependency?

**Comment by JKRhb** [comment]
> @JKRhb do you think a _similar_ fix is needed for a modbus dependency?

Hmm, good question, I personally haven't run into issues with modbus locally (using Node 20), maybe we can check if the problem persists once the mbus issues have been resolved.
