### ISSUE TITLE
Check need for ProtocolHelpers updatePropertyFormWithTemplate/updateActionFormWithTemplate/updateEventFormWithTemplate calls

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1031]
> If I recall correctly those set of methods are meant to update the form generated by the binding, trying to fulfill what the user set in the `PartialTD` passed in the `produce` method. My guess, is that using them in two different bindings causes some possible collisions 🤔 . However, the methods are poorly implemented and I think we should review them in the future. I propose merging this PR and keeping track of this issue.

_Originally posted by @relu91 in https://github.com/eclipse-thingweb/node-wot/issues/1026#issuecomment-1595812182_

**Comment by relu91** [comment]
I opened #1029 to track the same point. Closing this issue, feel free to re-open if you had another goal in mind.

**Comment by danielpeintner** [comment]
Sorry, missed that 🤦‍♂️
