### ISSUE TITLE
Strict boolean expressions

### ISSUE THREAD

**Issue by relu91** [eclipse-thingweb/node-wot#1046]
> We probably need to scan the whole codebase for cases like these at some point – IIRC, there are a number of places where we check for "falsy" values instead of `undefined` or `null`. I think there is the possibility to make the eslint rules a bit stricter in this regard to help us with that.

_Originally posted by @JKRhb in https://github.com/eclipse-thingweb/node-wot/pull/1042#discussion_r1277735531_

As mentioned above, we are not currently verifying that our codebase uses the boolean expressions correctly. As we all know the nullish values can sometimes by tricked and led us to unwanted bugs (as the bugs that the PR above was solving). I tried to enable  `"@typescript-eslint/strict-boolean-expressions": "error"` into our eslint file, but that requires `strictNullChecks` to be enabled in `tsconfig.json`. Therefore, I suggest first completing the long standing #758 and then looking back to this issue. 

Packages to be fixed:
- [x] binding-coap
- [ ] binding-modbus
- [ ] browser-bundle
- [ ] binding-file
- [ ] binding-mqtt
- [ ] cli
- [ ] binding-netconf
- [x] core
- [ ] binding-opcua
- [x] examples
- [ ] binding-websocket
- [x] td-tools
- [x] binding-http
- [ ] binding-mbus

**Comment by danielpeintner** [comment]
I suggest to fix the issue step by step like in https://github.com/eclipse-thingweb/node-wot/issues/758. That's why I added the "packages to be fixed list" above
