### ISSUE TITLE
Node.js 21 has been released recently

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1131]
Shall we add CI tests for it?
https://github.com/eclipse-thingweb/node-wot/blob/c14d4ddc5274fbacb3565091aecb11b33c11466f/.github/workflows/ci.yaml#L18

**Comment by relu91** [comment]
Given that Node.js was just a ["quick" version](https://nodejs.org/en/about/previous-releases) and it's going to go out of maintenance soon (plus we are also working on #1274 - Node version 22). I would close this issue.
