### ISSUE TITLE
OPCUA test issues with MacOS

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1138]
We recently re-introduced the CI tests for Windows and MacOS again (see https://github.com/eclipse-thingweb/node-wot/pull/1121),

By doing so we now have somewhat consistently failings tests for OPCUA on MacOS.
see for example https://github.com/eclipse-thingweb/node-wot/actions/runs/6625217554/job/17995749117?pr=1137#step:6:416

@erossignon do you have an idea what might causing these problems?

**Comment by erossignon** [comment]
I'll take it, 
It seems the vm doesn't have the domain name properly installed
os.hostname() has a ".local" suffix added that causes problem.

**Comment by erossignon** [comment]
After digging, it appears to me that the `/etc/hosts` file doesn't have an entry with the hostname of the machine by default.

Adding  `127.0.0.1  <hostname>` in the /etc/hosts fixes this.

**Comment by danielpeintner** [comment]
resolved by https://github.com/eclipse-thingweb/node-wot/pull/1141

**Comment by erossignon** [comment]
It's pretty annoying that this PR was not merged but has been replaced with a different one that does the same thing by a reviewer of this PR. This is not the find time that this is happening.

Are you still accepting external contributions to the project? Do you value the time and effort of your contributors ?
