### ISSUE TITLE
TDParser - strange behavior with unusual base URI

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1139]
I have encountered a _strange_ behavior with our TDParser.

Let's assume I have the following TD with the unusual `base`.

```
{
    "@context": "https://www.w3.org/2022/wot/td/v1.1",
    "title": "TestModbus",
    "base": "modbus+tcp://##addr##:502/##unitid##",
    "securityDefinitions": {
      "nosec_sc": {
        "scheme": "nosec"
      }
    },
    "security": "nosec_sc",
    "properties": {
      "voltage": {
        "title": "Voltage",
        "type": "number",
        "forms": [
          {
            "href": "/40001?quantity=2"
          }
        ]
      }
    }
  }
```

If I do `TDParser.parseTD(...)` I would assume that `href` for the property `voltage` is
* "/40001?quantity=2"
   or
* "modbus+tcp://##addr##:502/##unitid##/40001?quantity=2"

What I get is "modbus+tcp:///40001?quantity=2"

Somehow parts get stripped off!?

**Comment by danielpeintner** [comment]
It is a problem of this line / library

https://github.com/eclipse-thingweb/node-wot/blob/247b0d48d69962263d994b91d1ff0097c5056be0/packages/td-tools/src/td-parser.ts#L211

What do people think? Is this a bug in the library?
I assume the URL is not valid (not sure if there is a good mean to check that).

I wonder whether we should really do such checks !?

**Comment by danielpeintner** [comment]
The problem is BIGGER than I thought.. it seems that the library does not work for straightforwards base URLs.

e.g., PR  https://github.com/eclipse-thingweb/node-wot/pull/1140
base: "modbus+tcp://192.168.178.123:502/unitid"
relative href: "/40001?quantity=2"
leads to the following absolute URI "modbus+tcp://192.168.178.123:502/40001?quantity=2"

Somehow everything after the port 502 (in this case "/unitid") gets stripped off from the base.

**Comment by egekorkan** [comment]
One part of the problem is the definition of the relative URL. If a relative URL starts with / , it replaces everything starting after port. However, it does not explain why even the hostname (`##addr##:502`) gets removed. The behaviour in the comment just above is correct.

**Comment by danielpeintner** [comment]
> One part of the problem is the definition of the relative URL. If a relative URL starts with / , it replaces everything starting after port.

I see... I missed that 👍

**Comment by danielpeintner** [comment]
The base `modbus+tcp://##addr##:502/##unitid##/` is still not properly handled.

**Comment by danielpeintner** [comment]
The actual issue is that # has a special meaning in the context of an URL (i.e., fragment identifier).
Hence we should not use it in this context.
