### ISSUE TITLE
Interface SMC should use valid idShort values

### ISSUE THREAD

**Issue by sebastiankb** [eclipse-thingweb/node-wot#1145]
Currently, the proposed generated idShort value for the interface SMC takes over a character that is not allowed in AAS:

![image](https://github.com/eclipse-thingweb/node-wot/assets/13832739/98b1956c-0afb-494d-9a86-fc04769b21d2)

So, the "+" character is not allowed and should be replaced with "_".

**Comment by danielpeintner** [comment]
Is there a list of _not_ allowed characters ?
