### ISSUE TITLE
security should be a list of References

### ISSUE THREAD

**Issue by sebastiankb** [eclipse-thingweb/node-wot#1146]
The AID specification defines "security" as SML of references. The node-wot still uses the "old" AID version of SMC with property definitions:

![image](https://github.com/eclipse-thingweb/node-wot/assets/13832739/c9fe6872-bc83-48fd-a0ed-2918da40008e)

The SML version have references that points to the used securityDefinitions, e.g.:

![image](https://github.com/eclipse-thingweb/node-wot/assets/13832739/ef288317-1832-4098-b4c5-1489ede38eb0)

The corresponding  implementation for the `nosec_sc` path reference will be: 

```js
{
              "idShort": "security",
              "typeValueListElement": "SubmodelElement",
              "value": [
                {
                  "value": {
                    "type": "ModelReference",
                    "keys": [
                      {
                        "type": "Submodel",
                        "value": "https://i.siemens.com/demo/ids/sm/aid/1P7KM4212-0BA00-..."
                      },
                      {
                        "type": "SubmodelElementCollection",
                        "value": "InterfaceMODBUS_TCP"
                      },
                      {
                        "type": "SubmodelElementCollection",
                        "value": "EndpointMetadata"
                      },
                      {
                        "type": "SubmodelElementCollection",
                        "value": "securityDefinitions"
                      },
                      {
                        "type": "SubmodelElementCollection",
                        "value": "nosec_sc"
                      }
                    ]
                  },
                  "modelType": "ReferenceElement"
                }
              ],
              "modelType": "SubmodelElementList"
            }
```

The Submodel value is the ID of the AID Submodel. Here, it would be good, when a individual Submodel ID can be submitted for the `transformTD2SM` method. If not, a default version will be used.

**Comment by danielpeintner** [comment]
> The Submodel value is the ID of the AID Submodel. Here, it would be good, when a individual Submodel ID can be submitted for the transformTD2SM method. If not, a default version will be used.

It uses the id of the TD (if present). Hence I think the option to set it is already there...
