### ISSUE TITLE
CLI not loading the script

### ISSUE THREAD

**Issue by relu91** [eclipse-thingweb/node-wot#1151]
As demonstrated by the latest [live coding](https://www.youtube.com/live/2eUOk0oE5vo?si=ZLcT70nNHaj7NoX_&t=2054), when you call `wot-servient script.js` nothing happens and the script is not run.

**Comment by danielpeintner** [comment]
I never run the CLI with `wot-servient`. Anyhow, running a sample like this

`node packages\cli\dist\cli.js examples\scripts\counter.js`

throws the following error.

```
Error: Cannot produce ExposedThing because " + #<Object> could not be cloned.
    at ...\packages\core\dist\wot-impl.js:111:24
    at new Promise (<anonymous>)
```

and my guess is that it has to do with https://github.com/eclipse-thingweb/node-wot/pull/1105.

I will try to take a look unless @JKRhb will look into... please let me know...
