### ISSUE TITLE
[http-binding] https-based connections for a client implemention should work without servient.addCredentials()

### ISSUE THREAD

**Issue by sebastiankb** [eclipse-thingweb/node-wot#1158]
# What

A server that offers a TD with https scheme should usually not require any additional credentials, as the underlying TLS process exchanges the certificates in the background between server and client. 

If I setup node-wot for this scenario as client, I cannot use simple the two liner

```js
let servient = new Servient();
servient.addClientFactory(new HttpsClientFactory(null));
```

When I run the code, there is an error message:

`TypeError: Cannot destructure property 'username' of 'undefined' as it is undefined.`

However, when I add 

```js
servient.addCredentials({
    "urn:dev:wot:org:eclipse:thingweb:my-example-secure": {
        username: "node-wot",
        password: "hello"
    },
});
```
with random username and password values, the communication works.

# How

A simple client connection via https should simple need this few lines of codes:

```js
let servient = new Servient();
servient.addClientFactory(new HttpsClientFactory(null));
```
Username and password should not needed.

**Comment by danielpeintner** [comment]
I _think_ node-wot is doing the right thing, but let me try to ask some questions first.

Can you share the security settings used? Can it be that you do something like this in the consumed TD?

```
    "securityDefinitions": {
        "basic_sc": {"scheme": "basic"}
    },
    "security": "basic_sc",
```

Once you setup `basic` security scheme it requires  [username and password](https://w3c.github.io/wot-thing-description/#basicsecurityscheme).

I think in the case of no need for username and password something like this should work.

```
    "securityDefinitions": {
        "nosec_sc": {"scheme": "nosec"}
    },
    "security": "nosec_sc",
```
 
Please confirm whether my guesses are correct?

**Comment by sebastiankb** [comment]
You are right. I had a basic scheme in my TD 🙈

 So the behavior of node-wot was correct. When I change my TD to nosec, `addCredentials` is not needed anymore.

Close this issue.
