### ISSUE TITLE
CI: Combination of MacOS and MQTT failing

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1159]
The recent days I noticed that MQTT tests are failing for for CI builds (I think mainly on MacOs).

e.g.,
* https://github.com/eclipse-thingweb/node-wot/actions/runs/6823627505/job/18557909297#step:8:401
* https://github.com/eclipse-thingweb/node-wot/actions/runs/6732890771/job/18300446252?pr=1149#step:7:401
* ...

Note: re-running the CI for failed jobs usually works.

pinging [@egekorkan](https://github.com/egekorkan) [@sebastiankb](https://github.com/sebastiankb) [@hasanheroglu](https://github.com/hasanheroglu) as MQTT mainatainers

**Comment by danielpeintner** [comment]
Note: Once the issue is resolved we should remove the skipping tests in https://github.com/eclipse-thingweb/node-wot/pull/1181

**Comment by danielpeintner** [comment]
Since the MQTT tests are still failing I wonder whether we should _re-activate_ https://github.com/eclipse-thingweb/node-wot/pull/1181

Note: Tests are not failing on MacOS only, also on Ubuntu/Windows etc..
see https://github.com/eclipse-thingweb/node-wot/actions/runs/7260776357/job/19780615145

**Comment by danielpeintner** [comment]
It is still very much annoying that MQTT tests fail randomly. Are we okay to skip MQTT tests for now or do you prefer to see for each PR etc failings tests?

**Comment by egekorkan** [comment]
Done as of #1272
