### ISSUE TITLE
Stop Updating Copyright Years

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1170]
I start thinking that the effort of updating copyright years over and over again is **not** worth it.

In node-wot the year indicates when a file was last updated. In dart_wot the year indicates when a file was created (see https://github.com/eclipse-thingweb/dart_wot/pull/68#issuecomment-1806094381).

Other people/companies/organizations start to think we should not do that any longer, see https://hynek.me/til/copyright-years/

Any opinions?

**Comment by egekorkan** [comment]
I think I was in the bandwagon of "that's what we always did..." but I'm fine to change. What about other Eclipse projects though? I can ask helpdesk too.

**Comment by egekorkan** [comment]
As mentioned in the handbook, we should have been using the year of creation: https://www.eclipse.org/projects/handbook/#ip-copyright-headers . I will ask what to do with transferred repositories such as playground and dart_wot. For node-wot, we should use the creation year.
