### ISSUE TITLE
Inconsistent way of importing classes in examples 

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1187]
e.g. HTTP
https://github.com/eclipse-thingweb/node-wot/blob/7334567c2c531dfec25cab0b5d9a9aa943176167/packages/binding-http/README.md?plain=1#L29-L30

vs. CoAP
https://github.com/eclipse-thingweb/node-wot/blob/7334567c2c531dfec25cab0b5d9a9aa943176167/packages/binding-coap/README.md?plain=1#L29-L30

or also in the same file in root README

https://github.com/eclipse-thingweb/node-wot/blob/7334567c2c531dfec25cab0b5d9a9aa943176167/README.md?plain=1#L144-L146

vs.

https://github.com/eclipse-thingweb/node-wot/blob/7334567c2c531dfec25cab0b5d9a9aa943176167/README.md?plain=1#L182-L184

I think we should agree on the "proposed" way!

**Comment by JKRhb** [comment]
I think I would prefer the 

```ts
 const { Servient, Helpers } = require("@node-wot/core"); 
 const { HttpClientFactory } = require('@node-wot/binding-http'); 
```

approach since it looks a bit cleaner and also avoids some redundancy.

**Comment by egekorkan** [comment]
Agreeing with @JKRhb direction. Also, this would promote "better" code since with the other approach one can write `const BestServer = require('@node-wot/binding-http').HttpServer;`
