### ISSUE TITLE
Follow-up octet-stream codec - short explanation

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1194]
> Thank you very, much for your efforts! We can merge it and try to play with it. As a follow-up work, we should provide a short explanation about the new terms introduced.

_Originally posted by @relu91 in https://github.com/eclipse-thingweb/node-wot/pull/1125#pullrequestreview-1783480216_

**Comment by derwehr** [comment]
I can write up explanations for the added terms along with examples. Where would be the correct place to add the descriptions?

**Comment by danielpeintner** [comment]
> I can write up explanations for the added terms along with examples. Where would be the correct place to add the descriptions?

We have READMEs for each package. Hence I suggest to enhance the [core README](https://github.com/eclipse-thingweb/node-wot/blob/master/packages/core/README.md) with a subsection of "Codecs" in which you can explain the octet-stream codec.

@relu91 @JKRhb I hope this is fine by you as well... otherwise we can move around the description
