### ISSUE TITLE
Changes update of Asset Interfaces Description (AID) submodel 

### ISSUE THREAD

**Issue by Kaz040** [eclipse-thingweb/node-wot#1220]
Hello @danielpeintner, this issue is mainly intended to track changes made from the last AID implementation in node-wot.

 latest changes as of January 18, 2024
 
# Changes in AID from last implementation

|#| IdShort (Term) | Parent(s) | Protocol Specific | What changed | result |
|:-|:-              |:-      |:-                 |:-            |:-      |
|1 |created |Interface SMC | No| SemanticID | http://purl.org/dc/terms/created |
|2 |modified|Interface SMC | No| SemanticID | http://purl.org/dc/terms/modified |
|3 |support |Interface SMC | No| SemanticID| https://www.w3.org/2019/wot/td#supportContact |
|4 |base    |EndpointMetadata SMC | No| SemanticID | https://www.w3.org/2019/wot/td#baseURI |
|5 |scheme | SecurityDefinitions SMC | No| SemanticID | https://www.w3.org/2019/wot/security#SecurityScheme |
|6 |InterfaceMetadata |InterfaceSMC | No| idShort | InteractionMetadata |
|7 |InterfaceMetadata |InterfaceSMC | No| SemanticID | https://admin-shell.io/idta/AssetInterfacesDescription/1/0/InteractionMetadata |
|8 |modbus_function |forms SMC | Yes --> MODBUS| idShort |modv_function |
|9 |modbus_function |forms SMC | Yes --> MODBUS| SemanticID |https://www.w3.org/2019/wot/modbus#hasFunction |
|10 |modbus_type |forms SMC | Yes --> MODBUS| idShort |modv_type |
|11 |modbus_type |forms SMC | Yes --> MODBUS|SemanticID |https://www.w3.org/2019/wot/modbus#hasPayloadDataType |
|12 |modbus_entity |forms SMC | Yes --> MODBUS| idShort |modv_entity |
|13 |modbus_entity |forms SMC | Yes --> MODBUS|SemanticID |https://www.w3.org/2019/wot/modbus#hasEntity |
|14 |modbus_pollingTime |forms SMC | Yes --> MODBUS| idShort |modv_pollingTime |
|15 |modbus_pollingTime|forms SMC |Yes --> MODBUS|SemanticID |https://www.w3.org/2019/wot/modbus#hasPollingTime |
|16 |modbus_timeout |forms SMC | Yes --> MODBUS| idShort |modv_timeout |
|17 |modbus_timeout |forms SMC |Yes --> MODBUS|SemanticID |https://www.w3.org/2019/wot/modbus#hasTimeout |
|18 |modbus_zeroBasedAddressing |forms SMC | Yes --> MODBUS| idShort |modv_zeroBasedAddressing |

# New Terms included in AID

|#| IdShort (New Term) | Parent(s) | Protocol Specific | SemanticID | 
|:-|:-              |:-      |:-                 |:-            |
|1 |modv_mostSignificantByte |EndpointMetadata SMC and forms SMC | Yes --> MODBUS| https://www.w3.org/2019/wot/modbus#hasMostSignificantByte| 
|2 |modv_mostSignificantWord|EndpointMetadata SMC and forms SMC | Yes --> MODBUS|https://www.w3.org/2019/wot/modbus#hasMostSignificantWord |

**Comment by danielpeintner** [comment]
> latest changes as of January 18, 2024

Question: @Kaz040 are there possibly more changes coming or can I take this list as finite?
