### ISSUE TITLE
AID - Terms on affordance level and form level

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1225]
For optimization reasons AID has the possibility to set certain terms on affordance **and** `form` level while the TD allows such terms on form level only, e.g.:
* `contentType`
* `mostSignificantByte` (Modbus)
* `mostSignificantWord` (Modbus)

We should check whether we handle those cases properly and create test cases for it.
Note: Maybe TD2.0 will allow for similar optimizations.

@Kaz040 are there more such terms, maybe also for other protocols besides Modbus?

**Comment by Kaz040** [comment]
> are there more such terms, maybe also for other protocols besides Modbus?

@danielpeintner, for now it is only those three terms. I think more might follow when we start looking into other protocols. I will update this issue once there is an additional term so that we can a place to track them.
