### ISSUE TITLE
InteractionOutput.value() throws an error for Actions with no output DataSchema

### ISSUE THREAD

**Issue by FadySalama** [eclipse-thingweb/node-wot#1228]
I encountered this problem while interacting with the [TestThing](http://plugfest.thingweb.io:8083/testthing). When invoking the ``"void-void"`` action, the action results in an ``505: Internal Server Error`` with the message ``No schema defined``. This is thrown inside ``value()``  as seen below:

https://github.com/eclipse-thingweb/node-wot/blob/82f7f7acd1e68f80af9b53e9ef623d9a83334a39/packages/examples/src/testthing/testthing.ts#L240

As no data schema is needed for an action with no output, calling ``value()`` on the interaction output throws an error. However, this behavior seems a little counterintuitive. I would think, intuitively, that an action without an ``output`` ``DataSchema`` would either provide no ``InteractionOutput`` at all or would provide and ``InteractionOutput`` with a ``value()`` method that resolves with ``undefined`` and an ``arrayBuffer()`` method that resolves with an empty array (maybe also ``undefined`` but it makes more sense you would actually get an array, but it's empty because there is no output).

**Comment by danielpeintner** [comment]
We could look whether a schema is available at all

https://github.com/eclipse-thingweb/node-wot/blob/82f7f7acd1e68f80af9b53e9ef623d9a83334a39/packages/core/src/interaction-output.ts#L94

Hence, we should not do anything if `this.schema == null ` and return `undefined` in such a case?

@relu91 @JKRhb any opinion?

**Comment by danielpeintner** [comment]
I created draft PR https://github.com/eclipse-thingweb/node-wot/pull/1230 to show what I mean...

**Comment by FadySalama** [comment]
Throwing an error if ```schema.type == null`` will throw in cases in which the schema is correctly defined using ``"oneof"``

**Comment by egekorkan** [comment]
> Throwing an error if `schema.type == null` will throw in cases in which the schema is correctly defined using `"oneof"`

Related to https://github.com/w3c/wot-scripting-api/pull/534

**Comment by relu91** [comment]
I think this is also related to satellite discussions: https://github.com/w3c/wot-thing-description/issues/1234 and in particular https://github.com/w3c/wot-thing-description/issues/1441. My opinion here is that the implementation is still correct, but we are lacking a way to clearly express the fact that we are expecting an empty payload.
