### ISSUE TITLE
Aligning ajv usage

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#1245]
Currently, there are two ajv inclusions in package.json. One is in core package and the other one is in opcua binding. They are using the same version, thankfully. However, the ajv-formats is not part of the core package, which results in the following warning message:

```sh
unknown format "date-time" ignored in schema at path "#"
```

This will result in node-wot not being able validate formats passed in the string data schema.

So I propose the following:
- removing ajv and ajv-formats dependency from binding-opcua
- Adding ajv-formats to core package as a dependency (see https://ajv.js.org/packages/ajv-formats.html). 

Until TD removes the format keyword, we have to support it in one way or another in node-wot.

Also related to https://github.com/eclipse-thingweb/node-wot/issues/754

**Comment by danielpeintner** [comment]
> They are using the same version, thankfully.

FYI, the following script takes care to not have different versions
https://github.com/eclipse-thingweb/node-wot/blob/ad76c375b40d85875b9d88142ed0d49fc24d7dc4/package.json#L31

> So I propose the following:

That makes sense. Do you want to do that? I can make the change also if you like...
