### ISSUE TITLE
HTTP Client sends wildcard content type even if a form is selected

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#1246]
When a node-wot Consumer application consumes an HTTP Thing and has a readproperty call, HTTP binding is sending the wildcard `*/*` as the accept header. This is the case even if the formIndex is given. This is not totally wrong (I think) but I don't see a reason for it other than having less implementation effort for node-wot. On the other hand, Things can check for the header values based on the contentType they put in their form and not necessarily check for wildcards. 

You can see this happening at the test-things PR:

- TD: https://github.com/eclipse-thingweb/test-things/pull/16/files#diff-28802930bbd6a4a08dc9a75648dd2b65e6e796b53994373272279ee0bd83893f
- Backend code: https://github.com/eclipse-thingweb/test-things/pull/16/files#diff-dfa34653e484ae5a096b83e85021837f4d7ad5266627de440355e56b7bc29842R215

What do the others think? Should we also raise the discussion in the standardization?

Note: This does not happen in coap binding

**Comment by JKRhb** [comment]
So the consumer does not use the `contentType` from the form at all and always uses `*/*`, right? If so, that definitely seems looks a bug. However, apparently the [binding template](https://w3c.github.io/wot-binding-templates/) does not mandate any kind of mapping from form terms to headers and you can only specify headers that should be used within `htv:MessageHeader`. So this behavior seems to actually be specification-compliant, as `*/*` is equivalent to no accept header value (if I understood [RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-5.3.2) correctly).

Maybe we can also define some kind of mapping for HTTP here as well, similar to the mapping from form terms to CoAP options we now have in the CoAP Binding Template.

**Comment by relu91** [comment]
I didn't check the details but is this discussion related to https://github.com/eclipse-thingweb/node-wot/issues/854 ?

**Comment by egekorkan** [comment]
> Maybe we can also define some kind of mapping for HTTP headers here as well, similar to the mapping from form terms to CoAP options we now have in the CoAP Binding Template?

Definitely agree.

> I didn't check the details but is this discussion related to https://github.com/eclipse-thingweb/node-wot/issues/854 ?

Yes. I will close this one and continue there.
