### ISSUE TITLE
Moving AID tooling to td-tools repository

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#1249]
In the call today, we agreed on starting this. 

* [X] PR to td-tools will be created
  (see https://github.com/eclipse-thingweb/td-tools/pull/7)
* [X] name will be `@thingweb/aas-aid` and pushed on NPM, pushed on https://www.npmjs.com/package/@thingweb/aas-aid
* [x] PR to delete AID tooling and updating [td-tools level readme](https://github.com/eclipse-thingweb/node-wot/tree/master/packages/td-tools), as well as pointing to new place at https://github.com/eclipse-thingweb/node-wot/tree/master/packages/td-tools/src/util. This last readme will stay for a while since IDTA standardization group has the link to that readme location.
  (see https://github.com/eclipse-thingweb/node-wot/pull/1256)
* [X] Closing https://github.com/eclipse-thingweb/node-wot/issues/1235, done in td-tools, see https://github.com/eclipse-thingweb/td-tools/pull/7
* [x] Other
   * Add link to https://github.com/admin-shell-io/submodel-templates/tree/main/published/Asset%20Interfaces%20Description/1/0
   * ...

**Comment by danielpeintner** [comment]
Reopen since one checkbox is not yet done

**Comment by egekorkan** [comment]
Last one also done, closing
