### ISSUE TITLE
CI - Add Node.js 22 to CI tests

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1273]
Node.js 22 is now available!
see https://nodejs.org/en/blog/announcements/v22-release-announce

We might want to add it to our CI tests in https://github.com/eclipse-thingweb/node-wot/blob/master/.github/workflows/ci.yaml

**Comment by relu91** [comment]
Introduced tests for Node 22 https://github.com/eclipse-thingweb/node-wot/pull/1302. Let's close.
