### ISSUE TITLE
CoAP issue on local machine (Windows) - nO 

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1276]
Since a while I am seeing always this failure. I never saw it on a CI run.

![image](https://github.com/eclipse-thingweb/node-wot/assets/11281461/3da18f3b-420c-481d-aedf-3206f448c71b)

Since it doesn't get away I just document here... if it is just my setup I think we can leave it as is.

**Comment by egekorkan** [comment]
Could it be that you have another service is running on port 9000 that didn't use to run before?

**Comment by danielpeintner** [comment]
That's a good point. Changing it to another port like 9123 resolves the issue 👍
