### ISSUE TITLE
Modbus Test issue with modv:function

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1287]
VS Code shows me an error that 255 is not correct
https://github.com/eclipse-thingweb/node-wot/blob/be63265c8bf9f0c3882282b619ee5c67e1b0526a/packages/binding-modbus/test/modbus-client-test.ts#L272

![image](https://github.com/eclipse-thingweb/node-wot/assets/11281461/781cfc9a-2c5c-4399-bbf9-68b154d47887)

@relu91

**Comment by relu91** [comment]
given the test type I would change it to something like this:
```ts
const form: {
    href: "....",
    "modv:function": 255,
}
// other code here
```
