### ISSUE TITLE
Replacing Protocol and Port Detection

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#1307]
With https://www.npmjs.com/package/@thingweb/td-utils published, we can use it here and replace the old code at td-helpers with this.

**Comment by hasanheroglu** [comment]
I'll handle this.

**Comment by hasanheroglu** [comment]
Is there any other function that helps with this, except findProtocol and findPort in td-helpers.ts? If not, existing functions are unused, so I just remove them.
