### ISSUE TITLE
core package is missing dependencies in v0.8.15

### ISSUE THREAD

**Issue by hasanheroglu** [eclipse-thingweb/node-wot#1317]
[serdes.ts](https://github.com/eclipse-thingweb/node-wot/blob/master/packages/core/src/serdes.ts) uses two dependencies `is-absolute-url` and `url-toolkit` which are not included in core's [package.json](https://github.com/eclipse-thingweb/node-wot/blob/master/packages/core/package.json). Since td-tools package installs those two dependencies it may seem working in the monorepo but when it is installed alone it causes an error.

**Comment by danielpeintner** [comment]
Mhh, the problem was surely introduced in https://github.com/eclipse-thingweb/node-wot/pull/1312 and I will provide a fix soon.

I wonder whether there is a way to detect such an issue ... any ideas ?

**Comment by hasanheroglu** [comment]
We can separate CI runs for each package. We install only package-specific and root dependencies (devDependencies of the root package.json), run the test, and see if it passes.

**Comment by relu91** [comment]
> We can separate CI runs for each package. We install only package-specific and root dependencies (devDependencies of the root package.json), run the test, and see if it passes. I can work on this if it makes sense for you.

I'm curious to see a concrete PR on this, but I'm afraid it will get quite complicated to maintain and defeat the advantages of having a mono repo.

**Comment by danielpeintner** [comment]
FYI, v0.8.16 has been published.
