### ISSUE TITLE
Detect issue with dependencies in monorepo

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1319]
> I wonder whether there is a way to detect such an issue ... any ideas ?

We can separate CI runs for each package. We install only package-specific and root dependencies (devDependencies of the root package.json), run the test, and see if it passes. I can work on this if it makes sense for you.

_Originally posted by @hasanheroglu in https://github.com/eclipse-thingweb/node-wot/issues/1317#issuecomment-2301483122_

**Comment by relu91** [comment]
Ah didn't see that the issue was moved here. See https://github.com/eclipse-thingweb/node-wot/issues/1317#issuecomment-2302050845
