### ISSUE TITLE
WoT consume returns an implementation instead of an interface

### ISSUE THREAD

**Issue by RobWin** [eclipse-thingweb/node-wot#1331]
Hi,
is this correct in the WoT impl ?

The `WoT.produce` function returns an interface `WoT.ExposedThing? 
https://github.com/eclipse-thingweb/node-wot/blob/master/packages/core/src/wot-impl.ts#L125

But `WoT.consume` function returns an implementation class `ConsumedThing` instead of the interface `WoT.ConsumedThing`
Is this correct or a bug?

https://github.com/eclipse-thingweb/node-wot/blob/master/packages/core/src/wot-impl.ts#L104)

**Comment by danielpeintner** [comment]
I am still setting up my machine after a *forced* reinstall but just looking at the code on GitHub I would say it is fine as is.

An implementation can return an instance/implementation of an interface. `ConsumedThing`  `implements IConsumedThing` (FYI: the `IConsumedThing` is just named like this but is infact ConsumedThing  from `"wot-typescript-definitions"`)

Having said that, it might be better to change

`async consume(td: WoT.ThingDescription): Promise<ConsumedThing>`
to
`async consume(td: WoT.ThingDescription): Promise<WoT.ConsumedThing>`

for consistency reasons which should be fine also.. I will try after my toolchain is in place again.

**Comment by RobWin** [comment]
From a user perspective, if I retrieve a ConsumedThing implementation I have access to methods/functions which only the runtime should have access to.  
As a user I should only have access to the functions which are defined in the Scripting API, or not?

**Comment by RobWin** [comment]
Ok, now i understand.
I missed the line
`import { ConsumedThing as IConsumedThing, InteractionInput, Subscription } from "wot-typescript-definitions";`

But how does this code know it should return the interface and not the implementation? 

`const newThing: ConsumedThing = new ConsumedThing(this.srv, thing as ThingModel);`

Sry, I'm not an expert Typescript developer :(

**Comment by danielpeintner** [comment]
I will provide a PR that uses the interface (to be consistent).

**Comment by danielpeintner** [comment]
@RobWin I think https://github.com/eclipse-thingweb/node-wot/pull/1332/files should be what you expect to see, right?

**Comment by RobWin** [comment]
Yes, perfect
