### ISSUE TITLE
[binding-coap] observeproperty is not generated for CoAP forms

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#150]
When creating an exposed thing, in the generated forms for an observable property, no CoAP form with an op value of `observeproperty` is created. I think this is not a bug but something unexpected.  
To reproduce:
- Run `wot-servient counter.js`
- Check its TD via `http://localhost:8080/counter/`
- The count property has the following coap forms:
```json
        {
          "href": "coap://myip:5683/counter/properties/count",
          "contentType": "application/json",
          "op": [
            "readproperty"
          ]
        },
        {
          "href": "coap://myipv6:5683/counter/properties/count",
          "contentType": "application/json",
          "op": [
            "readproperty"
          ]
        },
```
- In the forms, there is no `observeproperty` in the op values.

**Comment by danielpeintner** [comment]
We could report `observeproperty` in a CoAP form just like we do for HTTP. However, the actual observe code is not implemented yet (see https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-coap/src/coap-server.ts#L238-L243).

Hence I do not think it makes sense, do you?

**Comment by egekorkan** [comment]
Ah ok, I would vote to leave this issue here until it is implemented? Binding templates have improved regarding this issue, see a preview [here](https://pr-preview.s3.amazonaws.com/w3c/wot-binding-templates/pull/80.html)

**Comment by relu91** [comment]
Checked with the [latest master](https://github.com/eclipse-thingweb/node-wot/commit/f972561cafb845627a50476f589eeb84c50fe2d7). The `observeproperty` is generated correctly. @egekorkan, feel free to re-open it if it is not working for you.
