### ISSUE TITLE
[binding-http] Support multiple security schema 

### ISSUE THREAD

**Issue by relu91** [eclipse-thingweb/node-wot#204]
Currently, the HTTP server supports only one security schema at the time. it would be more flexible if the user can configure multiple different schemas. I am not sure about a use-case, but since a TD could have a list of security definitions, I guess also the server must be able to handle such a scenario.

**Comment by egekorkan** [comment]
I would guess that a use case could be to provide two authentication mechanisms so that Consumers can choose the one they can use

**Comment by relu91** [comment]
@egekorkan  I guess this issue is a nice candidate to have a "good-first-issue" label.

**Comment by egekorkan** [comment]
Yes I agree, @danielpeintner could you create such a label?

**Comment by danielpeintner** [comment]
The label existed already.

Do you want to add it to the "useful labels" section in [README.md](https://github.com/eclipse/thingweb.node-wot/blob/master/README.md) also ?

**Comment by egekorkan** [comment]
Ah I see, I have no means to see the possible labels since I am not an official contributor. It would be nice to see them in Readme I guess :)

**Comment by danielpeintner** [comment]
> It would be nice to see them in Readme I guess :)

done

**Comment by nikosft** [comment]
I am wondering why security is implemented in the server and not in the thing, e.g., in `setActionHandler`. I see two issues.

 Firstly, the security configuration of the server seems independent of the used `securityDefinition` of the thing. 

Secondly, and more importantly, WoT Things description [allows the use of different _security_ per form](https://www.w3.org/TR/2020/REC-wot-thing-description-20200409/#form) (after all that's why securityDefinitions is an array) For example there can be both protected and not protected actions. I cannot see how this can be implemented using the current approach.

**Comment by egekorkan** [comment]
>  I cannot see how this can be implemented using the current approach.

I agree that the design of node-wot would not allow this without significant restructuring. I guess we never felt the need.

**Comment by relu91** [comment]
> I am wondering why security is implemented in the server and not in the thing, e.g., in setActionHandler.

My answer is that the application should not worry about security constraints. They should be handled by the runtime following what is specified in the TD. In fact, the ActionHandler does not have access to the underlying raw data provided by the protocol (i.e. headers).  I think changing this would require a change in the architecture specs 🤔 (see how security is embedded in the servient runtime [here](https://w3c.github.io/wot-architecture/#sec-building-blocks) )

> Firstly, the security configuration of the server seems independent of the used securityDefinition of the thing.

Servers might support only a subsets of security definitions. So when the application is exposing a Thing using not supported security protocol the runtime should throw an exception. Right now we are failing only if none of the provided security protocols are supported. Also, note that we are talking about the server-side and not the client-side. 

>Secondly, and more importantly, WoT Things description allows the use of different security per form (after all that's why securityDefinitions is an array) For example there can be both protected and not protected actions. I cannot see how this can be implemented using the current approach.

Yes, currently node-wot does not support security schema selection at the form level. This is another issue that should be reported separately in my opinion.

**Comment by nikosft** [comment]
> Right now we are failing only if none of the provided security protocols are supported

If the server is configured without any security mechanism, but TD defines a (supported) security protocol, what will happen? AFAIU, TD preference will be ignored.

**Comment by nikosft** [comment]
> My answer is that the application should not worry about security constraints. They should be handled by the runtime following what is specified in the TD. In fact, the ActionHandler does not have access to the underlying raw data provided by the protocol (i.e. headers). I think changing this would require a change in the architecture specs 🤔 (see how security is embedded in the servient runtime here )

I understand that currently security is built inside the protocol binding, which AFAICT is a violation of the architecture.
