### ISSUE TITLE
in subscribeEvent calling resolv for first(every in fact) event prevent to catch later error sent by reject.

### ISSUE THREAD

**Issue by franckOL** [eclipse-thingweb/node-wot#230]
https://github.com/eclipse/thingweb.node-wot/blob/7bcc1e651757c4f1f8e6814d64b30a2711add6f0/packages/core/src/consumed-thing.ts#L395

This a correct implementatin regarding the specification https://www.w3.org/TR/wot-scripting-api/#the-subscribeevent-method.

But how to deal with error happens during polling that need to resubscribe.

I try to remove resolv, and it works, of course i have now a perpetual unresolved promise (but catching polling error that happens)

**Comment by danielpeintner** [comment]
May I ask which binding do you use? CoAP?

**Comment by franckOL** [comment]
I use http-binding

**Comment by danielpeintner** [comment]
FYI: Related HTTP unsubscribe issue https://github.com/eclipse/thingweb.node-wot/pull/233.

I wonder whether a `else` branch is needed [here](https://github.com/eclipse/thingweb.node-wot/blob/7652a56c8d0dbb06b7c558bd52d2c05f47ebb534/packages/binding-http/src/http-client.ts#L186) calling 

`complete && complete()`

after the subscription is removed?
@egekorkan ?

**Comment by relu91** [comment]
I agree that after a successful unsubscribe the complete function should be called. As I said in https://github.com/eclipse/thingweb.node-wot/pull/233#issuecomment-635228354, we should also abort the pending HTTP GET, which may cause a throw [here](https://github.com/eclipse/thingweb.node-wot/blob/7652a56c8d0dbb06b7c558bd52d2c05f47ebb534/packages/binding-http/src/http-client.ts#L173). Consequently, inside the catch clause, we should handle the exception that indicates the cancellation and call the complete method there too. 

Like so we avoid pending resources which may be freed only after one hour: `{ timeout: 60 * 60 * 1000 }`.

**Comment by danielpeintner** [comment]
> we should also abort the pending HTTP GET, which may cause a throw [here](https://github.com/eclipse/thingweb.node-wot/blob/7652a56c8d0dbb06b7c558bd52d2c05f47ebb534/packages/binding-http/src/http-client.ts#L173). Consequently, inside the catch clause, we should handle the exception that indicates the cancellation and call the complete method there too.

If the line you cited throws we fall into the catch clause where we do already `error` and `complete`.
@relu91 not sure If I misunderstood your comment. Is there still anything missing there also?

**Comment by relu91** [comment]
If we cancel the ongoing HTTP GET request and `fetch` throws we should not call `error`. Therefore, we should handle this special error inside the `catch` clause. For example:
```javascript
}catch(e){
error && !isAbortError(e) && error(e)
....
}
```
Because in this case the error is generated by the unlink function and the user should not be notified. On the contrary, it indicates that the unsubscription is successful.

**Comment by danielpeintner** [comment]
> If we cancel the ongoing HTTP GET request and `fetch` throws we should not call `error`.

At the moment the PR does not try to cancel the HTTP GET. 

I did see your comment https://github.com/eclipse/thingweb.node-wot/pull/233#issuecomment-635228354 about aborting but I was unsure whether we want to do that.

**Comment by danielpeintner** [comment]
Still relevant?

**Comment by relu91** [comment]
> Still relevant?

I propose closing this issue for two reasons:
- `complete` function is currently not supported by the [Scripting API](https://w3c.github.io/wot-scripting-api/#ref-for-dom-consumedthing-subscribeevent-1). 
- In #1008 we introduced the concept of aborting the ongoing HTTP request when unsubscribing in long polling.

**Comment by danielpeintner** [comment]
Makes sense
