### ISSUE TITLE
Remove copyright script - replaced by eslint-plugin-notice

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#647]
see https://github.com/eclipse/thingweb.node-wot/pull/646#issuecomment-998037444

I suggest to keep the script some more weeks and IF we do not encounter any issues we can simply remove the content under
https://github.com/eclipse/thingweb.node-wot/tree/master/utils/fix-copyright

**Comment by danielpeintner** [comment]
I looked at some recent PRs and the copyright header is not properly updated.

e.g., https://github.com/eclipse/thingweb.node-wot/pull/660/files

@relu91 shouldn't it kick in automatically in VS and update the files accordingly? 
@JKRhb do you use VS code?

**Comment by JKRhb** [comment]
> I looked at some recent PRs and the copyright header is not properly updated.

Hmm, the way I understood the [Eclipse Foundation Handbook](https://www.eclipse.org/projects/handbook/#ip-copyright-headers) is that you only need the initial year in the copyright header and don't need to update it continuously:

> The {year} is the year in which the content was created (e.g. “2004”).

This is also the reason why I haven't checked the copyright statement manually. Do you actually need to refresh the year in the header?

> @JKRhb do you use VS code?

I actually do – I haven't noticed an automatic update, yet :/

**Comment by relu91** [comment]
The plug-in that I added warns you about missing license headers but it does not automatically add it when you create the file. Thanks to the eslint pipeline that we have (when it is restored) it should block PRs without the right header. The plug-in has also auto-fix feature so if you run `npm run lint -- --fix` should add the license header to all files without one.
