### ISSUE TITLE
node-wot metrics

### ISSUE THREAD

**Issue by wiresio** [eclipse-thingweb/node-wot#74]
It might be of use to find out about node-wot performance to check where there are possible bottlenecks if node-wot is part of a complete end-to-end setup. For that I'd like to have a module carrying out such measurements, like _counters of samples sent in the last 5 minutes_, _rate_, _throughput_, _total 5min-bytes_, _overall total bytes_ , etc.

**Comment by relu91** [comment]
Due to inactivity, we close the issue. Re-open if you have any concrete idea on how to do it. CC @danielpeintner
