### ISSUE TITLE
Update workspaces eslint plugin

### ISSUE THREAD

**Issue by relu91** [eclipse-thingweb/node-wot#751]
As I mentioned in #639, there was a small bug in the workspaces eslint plugin. Now that the bug is solved https://github.com/joshuajaco/eslint-plugin-workspaces/pull/17 we should update the dependency.

**Comment by relu91** [comment]
@danielpeintner does the new package-lock refer to the new version?

**Comment by danielpeintner** [comment]
No, I don't think so.. we still use
`"eslint-plugin-workspaces": "^0.7.0"`
in https://github.com/eclipse/thingweb.node-wot/blob/98a271052a2dd84afa71d8e73079d85a2449ac73/package-lock.json
and the version with the fix is 
`0.8.0-rc5`
