### ISSUE TITLE
`tsconfig.json` too benevolent

### ISSUE THREAD

**Issue by relu91** [eclipse-thingweb/node-wot#758]
This comment got me suspicious https://github.com/eclipse/thingweb.node-wot/pull/748#discussion_r871093794. `tsc` should be able to identify such trivial cases pretty well, so I further investigated. 

What I found is bad... we allowed the whole codebase to be not **strictly** checked. In other words, the root `tsconfig.json` contains `strict: false`. I think this got undercover when we unified all the tsconfigs in one using the composite build. 

Packages to be fixed:
- [x] binding-coap
- [x] binding-modbus
- [x] browser-bundle
- [x] binding-file
- [x] binding-mqtt
- [x] cli
- [x] binding-netconf
- [x] core
- [x] binding-opcua
- [x] examples
- [x] binding-websockets
- [x] td-tools
- [x] binding-http
- [x] binding-mbus
- ~~binding-fujitsu~~
- ~~binding-firestore~~
- ~~binding-firestore-browser-bundle~~

**Comment by danielpeintner** [comment]
Mhh, this is really bad. I quickly checked and there are many issues / warning 😌.
However, I suggest to clean-up the entire repo and all packages.. maybe tackle it package by package.. step by step

**Comment by relu91** [comment]
> I suggest to clean-up the entire repo and all packages.. maybe tackle it package by package.. step by step

yeah, I agree. I'll add some checkboxes to keep track of the progress

**Comment by relu91** [comment]
@JKRhb and @egekorkan since we are having a good sprint here, do you have time to tackle `binding-coap` and `binding-mqtt` ?

**Comment by relu91** [comment]
Binding netconf solved with #1071

**Comment by relu91** [comment]
We the final merge of #1059 we should now have the global strict set to true.
