### ISSUE TITLE
http client assumes http:methodName and does not look at @context

### ISSUE THREAD

**Issue by yagizyalcintas** [eclipse-thingweb/node-wot#80]
All the new examples of the TD standard uses:
```
    "@context": [
        "http://www.w3.org/ns/td",
        {"htv": "http://www.w3.org/2011/http#"}
    ]
... 
(in a form)
...
  "htv:methodName": "GET"
```
First problem is that the default assumption should be for `htv:methodName` and not `http:methodName` (or both). However, the recommended way would be to find the term that links to http context from `@context`. So even if someone uses:
```
    "@context": [
        "http://www.w3.org/ns/td",
        {"abc": "http://www.w3.org/2011/http#"}
    ]
... 
(in a form)
...
  "abc:methodName": "GET"
```
node-wot should be able to use the correct HTTP method.

http-client.ts looks for this at line 339.

**Comment by sebastiankb** [comment]
the prefix name should actually be independent. The actual namespace behind the prefix (= http://www.w3.org/2011/http#) is important. We need a generic processing of this.

**Comment by danielpeintner** [comment]
The TD (per default) has now `htv` bind to `http://www.w3.org/2011/http#`.

Hence I think
1. `htv:methodName` can be used without an additional `@context` definition
2. An additional `@context` definition such as `"abc": "http://www.w3.org/2011/http#"` should be still possible/allowed and needs to be processed properly by node-wot

**Comment by danielpeintner** [comment]
I wonder which is the better solution.

1. the _simpler_ approach of adding a JSON-LD library to node-wot that parses initially the provided TD and rewrites prefixes according to our understanding (e.g., `http://www.w3.org/2011/http#` to  to `htv`).
This means no big change in the rest of the code

2. an actual rewrite with passing `"@context"` array or the entire TD everywhere
(makes it also safer/better for possible future updates/changes)

**Comment by egekorkan** [comment]
I am not sure if I understand the first one since how could you know where to look at? What if I have a TD like the following:
```json
{
    "@context": [
        "https://www.w3.org/2019/wot/td/v1",
        { "wow": http://www.w3.org/2011/http#" }
    ],
    ...
    "properties": {
        "weather": {
            "forms": [{
              "href" : "http://example.org/weather",
              "wow:methodName": "GET"
            }]
        },
        ...
    },
    ...
}
```
I think the reason I am confused is because we don't necessarily need JSON-LD support here since we need to find where we have `http://www.w3.org/2011/http#` and replace `wow` with `htv` no?

**Comment by danielpeintner** [comment]
> I think the reason I am confused is because we don't necessarily need JSON-LD support here since we need to find where we have `http://www.w3.org/2011/http#` and replace `wow` with `htv` no?

You are right. We can walk over all JSON keys and replace any `"wow:"` with `"htv:"`. I was just thinking that this rewrite is better than with a library. I am not sure if there are (or can be) some corner cases that make it more difficult like
* "https://www.w3.org/2019/wot/td/v1" mapped to "td" and "http://www.w3.org/2011/http#" to default context et cetera
* ...

Shall we go with this simple rewrite solution?

**Comment by relu91** [comment]
Currently, in the spec, we force the prefix to be the one specified (e.g. for HTTP is `htv`, for modbus `modv`). This ensures the support for non-JSON-LD parsers. Closing the issue.
