### ISSUE TITLE
Slow tests

### ISSUE THREAD

**Issue by relu91** [eclipse-thingweb/node-wot#831]
After tinkering with #796 I found out that the most time-consuming activity in the CI is our tests. Usually, they take minutes even if sometimes in ubuntu they might be faster. We should pinpoint if there are any sleep or timeouts that we can remove and in general seek to improve the performance of our solution. 

As this issue is a little vague, I would add a concrete todo action:
- Verify the presence of timeouts and remove those wherever possible.

**Comment by relu91** [comment]
To ease the improvement we could also use: https://github.com/sinonjs/fake-timers

**Comment by danielpeintner** [comment]
From my side we can close the issue.
@relu91 ?

**Comment by relu91** [comment]
Checked one of the latest runs. Tests now complete in around 1 min and the delays are caused by long install time (see https://github.com/eclipse-thingweb/node-wot/actions/runs/8880185289/job/24379667144 - 4m to install). I think we reached a reasonable speed-up of our tests and we can close this issue now.
