### ISSUE TITLE
Http test should fail on ubuntu

### ISSUE THREAD

**Issue by relu91** [eclipse-thingweb/node-wot#837]
The error is: 
```
 https://127.0.0.1:3001/ failed, reason: connect ECONNREFUSED 127.0.0.1:3001
```
which should not happen and the test should fail. We have to understand why server is not responding in ubuntu

We have to investigate if this is a non-issue or if it is still happening on ubuntu. 
_Originally posted by @relu91 in https://github.com/eclipse/thingweb.node-wot/pull/830#discussion_r975336619_

**Comment by JKRhb** [comment]
Do you think this issue is still present in the current version?

**Comment by danielpeintner** [comment]
I tried locally with my Node.js v18.14.2 and we seem to get the _expected_ error message again. Hence I opened https://github.com/eclipse-thingweb/node-wot/pull/1111.

Let's see whether it runs fine on Node.js v20 also.
