### ISSUE TITLE
Documentation Discrepancy for HTTPS Server

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#839]
When looking at the readme at https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-http , I see that the HTTP server is configured as:
```js
servient.addCredentials({
    "urn:dev:wot:org:eclipse:thingweb:my-example-secure": {
        username: "node-wot",
        password: "hello",
        // token: "1/mZ1edKKACtPAb7zGlwSzvs72PvhAbGmB8K1ZrGxpcNM"
    },
});
let httpConfig = {
    allowSelfSigned: true, // client configuration
    serverKey: "privatekey.pem",
    serverCert: "certificate.pem",
    security: {
        scheme: "basic", // (username & password)
    },
};
// add HTTPS binding with configuration
servient.addServer(new HttpServer(httpConfig));
```

However, when looking at the JSON Schema of the config, the `serverKey` and `serverCert` are under the servient: https://github.com/eclipse/thingweb.node-wot/blob/master/packages/cli/src/wot-servient-schema.conf.json

At https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-http/src/http-server.ts#L103 , this config happens under HTTP so that must be the truth.

Then at https://github.com/eclipse/thingweb.node-wot/blob/master/packages/cli/wot-servient.conf.json.md there is no mention of these keys.

If it is indeed under HTTP, I will create a PR

**Comment by egekorkan** [comment]
I see. Depending on the outcome of #841, I can create a PR to fix it from documentation

**Comment by relu91** [comment]
> 

yes, let's merge #841 and fix this issue later.

**Comment by VigneshVSV** [comment]
I have an issue using the HttpsClientFactory 

```javascript
const { HttpsClientFactory } = require("@node-wot/binding-http");


const servient = new Servient();
servient.addClientFactory(new HttpsClientFactory({ 
        allowSelfSigned : true,
    }));

servient.start().then(async (WoT) => {
    const td = await WoT.requestThingDescription("https://localhost:8083/spectrometer/ocean-optics/USB2000-plus/resources/wot");
```

I get error:

FetchError: request to https://localhost:8083/spectrometer/ocean-optics/USB2000-plus/resources/wot failed, reason: self-signed certificate
    at ClientRequest.<anonymous> (H:\New Work\node-clients\serial-utility\node_modules\node-fetch\lib\index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'DEPTH_ZERO_SELF_SIGNED_CERT',
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}

The config does not seem to recognise self signed certificates despite asking so, 

Are these problems anyway related?

**Comment by danielpeintner** [comment]
Can/shall we update the JSON schema now? 
@egekorkan do you still plan to do so or shall  I go ahead?

**Comment by egekorkan** [comment]
@danielpeintner I had completely forgotten about this issue. If you can make a quick PR, it would be great 👍
