### ISSUE TITLE
Wrong list of collaborators in npm

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#946]
The collaborator list in npm packages seem outdated and do not vary based on package.

Even [core](https://www.npmjs.com/package/@node-wot/core) does not list @relu91 or [firestore](https://www.npmjs.com/package/@node-wot/binding-firestore) does not list @hidetak

**Comment by danielpeintner** [comment]
I think there is a misunderstanding w.r.t. terms.

![image](https://user-images.githubusercontent.com/11281461/229537485-913ce3e5-b970-4633-be74-4103cc08cbcf.png)

Collaborators for NPM are the ones that can update a package on NPM. The ones listed at the moment have been added *manually*. Moreover, you need a dedicated NPM account to be added. I don't think we can actually do much about that..

**Comment by egekorkan** [comment]
Ok so I have dug a bit deeper and it seems that collaborators are simply the members of an organization in npm. I would simply update this to be the list of project members in Eclipse (https://projects.eclipse.org/projects/iot.thingweb/who) . Requiring an npm account of course makes sense

**Comment by JKRhb** [comment]
I think via #986, this issue should be resolved, right?

**Comment by danielpeintner** [comment]
> I think via #986, this issue should be resolved, right?

Yes, we list the maintainers now in our GitHub repo.

On the NPM side (e.g., https://www.npmjs.com/package/@node-wot/td-tools) the "Collaborators" list is somewhat different but I don't think we can easily fix it.  On NPM we have a "node-wot" organization and we cannot specify different members on a package basis.

@egekorkan are you fine with closing this issue?

**Comment by egekorkan** [comment]
I still think that we should not close the issue and simply update the npm organization members. Why can we not easily fix it there?

**Comment by danielpeintner** [comment]
> Why can we not easily fix it there?

As said in my previous comment. We can add new members on the NPM side but then they will show up for all packages since it is **not** possible to add a a member for a single package in an organization.

**Comment by egekorkan** [comment]
By keeping the current structure, I think we should simply add @relu91 @JKRhb who maintain the packages regularly and remove the rest of the people except for @danielpeintner. It is not perfect but good enough for me.

However, there is a way to add further teams and more granular access control. It is not what we really want since in the end @danielpeintner publishes the packages and we should not allow the maintainers of a single package to publish a new version without the others. That granularity becomes more relevant in td-tools where the versions are not going to be synced.

**Comment by danielpeintner** [comment]
I am fine with what has been said, but I think this is a good topic for the committer meeting. Hence I added the label "Discuss in Committer Meeting"

**Comment by egekorkan** [comment]
Issue discussed and resolved in Committer Meeting
