### ISSUE TITLE
Deployed TestThing does not have readallproperties

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#949]
Testthing at http://plugfest.thingweb.io:8083/testthing does not have readallproperties operation listed even though it actually supports it, i.e. sending request to `http://plugfest.thingweb.io:8083/testthing/properties` returns all properties.

**Comment by relu91** [comment]
It might be a bug, we have to investigate more.

**Comment by danielpeintner** [comment]
While quickly checking I noticed some more things that do not seem correct.
* http://plugfest.thingweb.io:8083/counter/properties reports the properties but for all properties the value is wrapped into a string. Number should remain number and strings should not be wrapped in another string.
* Locally checking the counter sample  does report the following `{"count":"0","countAsImage":"\"2023-04-14T08:47:10.678Z\""}`. Wrapped values again **and** countAsImage reports the lastChange value !?
* Sidenode: I also think that http://plugfest.thingweb.io:8083/counter/properties/countAsImage should not report the SVG as text "<svg xmlns='http://www.w3.org/2000/svg' height='30' width='200'><text x='0' y='15' fill='black'>0</text></svg>". The surrounding quotes are not correct...

**Comment by egekorkan** [comment]
Even more mysterious: counter has readall and readmultiple whereas testthing has writeall and writemultiple

Also, writeall and writemultiple are not conforming to the TD spec. They do not seem to accept a single request to write into all the properties but as done in [consumed-thing.ts](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts#L625), all of them has to be written separately.
