### ISSUE TITLE
MQTT topic listener is not removed if the topic is unsubscribed

### ISSUE THREAD

**Issue by ilovemilk** [eclipse-thingweb/node-wot#955]
Hi everybody,

I noticed that there is a bug in the MQTT unsubscribe:

A listener is added if we subscribe to MQTT topic here:
https://github.com/eclipse/thingweb.node-wot/blob/adcd41e39e635c11d9a6e43e649e1de4acd56056/packages/binding-mqtt/src/mqtt-client.ts#L79

If we unsubscribe from a MQTT topic this listener is not removed with `this.client.off("message", callback)`:
https://github.com/eclipse/thingweb.node-wot/blob/adcd41e39e635c11d9a6e43e649e1de4acd56056/packages/binding-mqtt/src/mqtt-client.ts#L131-L133

For every subscription, we add an additional listener to the topic even if we unsubscribe the listener is still attached.

A possible fix could be a map of topics and attached listeners as we can not subscribe to the same topic twice. With this map, we can retrieve the callback and remove the listener in the `unlinkResource` method.

**Comment by danielpeintner** [comment]
@ilovemilk do you think you can work on a PR to solve the issue?

**Comment by egekorkan** [comment]
With #1184 this was fixed since now we have a pool to manage the connections. @ilovemilk please reopen if otherwise
