### ISSUE TITLE
Clear subscribers when needed

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#964]
Currently, if a longpoll-using affordance is getting subscriptions, if the client never unsubscribes, we start getting a memory leak:

> (node:20551) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Readable]. Use emitter.setMaxListeners() to increase limit

So we should clear the subscribers somewhat periodically (if an option is set?)

**Comment by relu91** [comment]
@egekorkan can you test with the latest node-wot? we should have improved the situation,  however long poll connections are cleared only after 1 hour: 
https://github.com/eclipse-thingweb/node-wot/blob/master/packages/binding-http/src/http-server.ts#LL1017C62-L1017C62

**Comment by egekorkan** [comment]
I am not seeing any error so I will close this and reopen if the issue is somehow not resolved
