### ISSUE TITLE
Tests take too long to time out

### ISSUE THREAD

**Issue by JKRhb** [eclipse-thingweb/node-wot#975]
In the context of https://github.com/eclipse/thingweb.node-wot/pull/963, I noticed once more that currently, the tests take much too long until they time out and free up the GitHub Actions resources again for a retry ([this workflow](https://github.com/eclipse/thingweb.node-wot/actions/runs/4886285729) took six hours to time out).

I think it would be nice if we could limit the timeout to a shorter duration, e.g. 5 or 10 minutes, to be able to re-run the pipeline much earlier. Maybe it is also an issue with the test configuration, though, since I would expect the tests to timeout after 30 to 60 seconds if they get stuck somewhere 🤔

**Comment by danielpeintner** [comment]
I noticed these issues as well... sometimes it takes a while till the workflow gets started (I think this is due to Eclipse limitations) and sometimes it gets stuck. I did not look into it but does someone know whether we can set a maximum limit for Github actions?

**Comment by relu91** [comment]
In my understanding, most of the tests have already a short timeout (the default should be 2000ms). As daniel said it might be something with the limitation of the service, but we should double-check if it wasn't actually our tests that got stuck.

**Comment by JKRhb** [comment]
With https://github.com/eclipse-thingweb/node-wot/pull/1175 and https://github.com/eclipse-thingweb/node-wot/pull/1178 merged, I think we can close this issue :)
