### ISSUE TITLE
(binding-coap) options field send as null to handleObserveProperty and handleUnobserveProperty

### ISSUE THREAD

**Issue by hasanheroglu** [eclipse-thingweb/node-wot#982]
https://github.com/eclipse/thingweb.node-wot/blob/09dfd6ab03805b7b39ab39433880496466d25e67/packages/binding-coap/src/coap-server.ts#L427-L442

`options` field send as null and leads to an error in the core package:
https://github.com/eclipse/thingweb.node-wot/blob/09dfd6ab03805b7b39ab39433880496466d25e67/packages/core/src/exposed-thing.ts#L621-L627
https://github.com/eclipse/thingweb.node-wot/blob/09dfd6ab03805b7b39ab39433880496466d25e67/packages/core/src/exposed-thing.ts#L653-L658

Is there a specific reason we send options field null here?

**Comment by egekorkan** [comment]
Just to be specific, the error pops up when trying to observe properties in coap

**Comment by relu91** [comment]
@JKRhb after the different refactorings is this issue handled?

**Comment by JKRhb** [comment]
Thank you for the ping, @relu91 :) During the refactoring, I actually noticed this bug as well and after double-checking, I think it should now be fixed! Therefore, I would close this issue – please leave a comment, @hasanheroglu, if you should notice that the issue persists!
